#!/usr/bin/env perl

use strict;
use warnings;
use File::Basename 'dirname';
use Cwd;
BEGIN{
  #$ENV{MOJO_MODE} ||= 'development';
  #$ENV{MOJO_MODE} = 'production';
  $ENV{MOJO_HOME} = Cwd::abs_path(dirname(__FILE__));
}

use lib ( "$ENV{MOJO_HOME}/lib");
#use lib ( "/path/to/lib");


# Check if Mojo is installed
eval 'use Mojolicious::Commands';
die <<EOF if $@;
It looks like you don't have the Mojo Framework installed.
Please visit http://mojolicious.org for detailed installation instructions.

EOF


# Application
$ENV{MOJO_APP} = 'Mojambo';

Mojolicious::Commands->start_app('Mojambo');

__END__


